#!/bin/bash

cd /home/lpe/TBtrapp/
lsof -t -i :5000 | xargs kill -9 #tue les processus en cours sur le port 5000

python2.7 serveur.py & #lance le serveur
sleep 10
/ferrari/ARCHIVES/Krystian/forbidden/firefox/firefox localhost:5000 #lance firefox sur le bon port
